# Generated by Django 4.2.21 on 2025-06-01 09:13

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('size', models.BigIntegerField()),
                ('reference_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'file_contents',
                'indexes': [models.Index(fields=['content_hash'], name='file_conten_content_316e80_idx')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(db_index=True, max_length=255)),
                ('file_type', models.CharField(db_index=True, max_length=100)),
                ('size', models.BigIntegerField(db_index=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_references', to='files.filecontent')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['original_filename'], name='files_origina_17f0ac_idx'), models.Index(fields=['file_type'], name='files_file_ty_08ab7b_idx'), models.Index(fields=['size'], name='files_size_9a2746_idx'), models.Index(fields=['uploaded_at'], name='files_uploade_83063c_idx'), models.Index(fields=['file_type', 'size'], name='files_file_ty_2a1c26_idx')],
            },
        ),
    ]
